"""
generate_demo_data.py

Creates synthetic (fake) customer journey data for "TechMart", a
fictional online electronics retailer. This is NOT real customer
data - every customer_id, timestamp, and event here is generated by
this script.

Run it directly to (re)create the demo CSV files in data/:
    python generate_demo_data.py

It produces three datasets, matching project brief section 34:
    demo_online_shopping_data.csv        - normal dataset with gaps
    demo_online_shopping_data_better.csv - includes enrichment fields
    demo_online_shopping_data_poor.csv   - fewer events, more gaps

Why simulate customers one at a time?
--------------------------------------
Real customer behaviour is a JOURNEY: each person either continues to
the next stage or drops off. Modelling it step-by-step (rather than
just generating random unconnected rows) is what makes the resulting
funnel numbers behave realistically, e.g. you can never have more
"payment" events than "checkout" events for the same customer.
"""

import random
from datetime import datetime, timedelta
import pandas as pd
import os

random.seed(42)  # fixed seed = same "random" data every time we run this

PRODUCT_IDS = [f"P{str(i).zfill(3)}" for i in range(1, 41)]
CHANNELS = ["website", "mobile_app"]

ABANDONMENT_REASONS = [
    "Price too high", "Changed my mind", "Found a better deal elsewhere",
    "Delivery cost too high", "Just browsing", "Technical issue at checkout",
]
PURCHASE_REASONS = [
    "Good price", "Fast delivery promised", "Trusted brand", "Product reviews", "Needed it urgently",
]


def _simulate_one_customer(customer_id, start_time, include_enrichment):
    """
    Simulate a single customer's path through the journey, stage by
    stage. At each stage, we roll a probability of continuing to the
    next stage - this is what creates realistic drop-off, rather than
    every customer behaving identically.
    """
    events = []
    product_id = random.choice(PRODUCT_IDS)
    channel = random.choice(CHANNELS)
    current_time = start_time

    def add_event(event_name, status="success", transaction_id="", order_id=""):
        events.append({
            "customer_id": customer_id,
            "timestamp": current_time.strftime("%Y-%m-%d %H:%M:%S"),
            "event": event_name,
            "product_id": product_id,
            "status": status,
            "channel": channel,
            "transaction_id": transaction_id,
            "order_id": order_id,
        })

    # Stage 1: everyone in this dataset at least discovers a product.
    add_event("product_discovery")
    current_time += timedelta(minutes=random.randint(1, 5))

    # Stage 2: product view (about 90% of discoverers view a product)
    if random.random() > 0.10:
        add_event("product_view")
        current_time += timedelta(minutes=random.randint(1, 10))
    else:
        return events, None  # dropped off before viewing

    # Stage 3: add to cart (~42% of viewers add to cart)
    if random.random() > 0.58:
        add_event("cart_add")
        current_time += timedelta(minutes=random.randint(1, 15))
    else:
        return events, None

    # Stage 4: checkout (~50% of cart-adders reach checkout)
    if random.random() > 0.50:
        add_event("checkout_start")
        current_time += timedelta(minutes=random.randint(1, 8))
    else:
        if include_enrichment:
            events.append({
                "customer_id": customer_id, "timestamp": current_time.strftime("%Y-%m-%d %H:%M:%S"),
                "event": "cart_add", "product_id": product_id, "status": "abandoned",
                "channel": channel, "transaction_id": "", "order_id": "",
                "abandonment_reason": random.choice(ABANDONMENT_REASONS),
            })
        return events, None

    # Stage 5: payment attempt (~90% of checkout-starters attempt payment)
    if random.random() > 0.10:
        transaction_id = f"TXN{customer_id}{random.randint(1000,9999)}"
        add_event("payment_attempt", transaction_id=transaction_id)
        current_time += timedelta(minutes=random.randint(1, 5))
    else:
        return events, None

    # Stage 6: payment succeeds ~91% of the time
    payment_succeeded = random.random() > 0.09
    if payment_succeeded:
        add_event("payment_success", transaction_id=transaction_id)
        current_time += timedelta(minutes=random.randint(1, 3))
    else:
        add_event("payment_failure", status="failed", transaction_id=transaction_id)
        return events, None

    # Stage 7: order confirmation (~97% of successful payments confirm)
    if random.random() > 0.03:
        order_id = f"ORD{customer_id}{random.randint(1000,9999)}"
        add_event("order_confirmation", transaction_id=transaction_id, order_id=order_id)
        current_time += timedelta(hours=random.randint(1, 4))
    else:
        return events, None

    # Stage 8: delivery (~93% of confirmed orders are delivered within the data window)
    if random.random() > 0.07:
        current_time += timedelta(days=random.randint(2, 7))
        add_event("delivery", order_id=order_id)
    else:
        return events, order_id

    # Stage 9: some delivered orders are returned (~12%)
    delivery_time = current_time
    if random.random() < 0.12:
        current_time = delivery_time + timedelta(days=random.randint(1, 10))
        add_event("return", order_id=order_id)

    # Stage 10: some delivered customers leave a review (~35%)
    if random.random() < 0.35:
        current_time = delivery_time + timedelta(days=random.randint(1, 14))
        add_event("review", order_id=order_id)

    if include_enrichment:
        events.append({
            "customer_id": customer_id, "timestamp": current_time.strftime("%Y-%m-%d %H:%M:%S"),
            "event": "purchase_reason_recorded", "product_id": product_id, "status": "info",
            "channel": channel, "transaction_id": transaction_id, "order_id": order_id,
            "purchase_reason": random.choice(PURCHASE_REASONS),
            "customer_satisfaction": random.randint(2, 5),
            "delivery_satisfaction": random.randint(2, 5),
        })

    return events, order_id


def generate_dataset(num_customers, include_enrichment=False, thin=False):
    """
    Generate a full synthetic dataset for `num_customers` customers.

    thin=True produces the "poor data" scenario: fewer optional
    columns and a shorter journey, to demonstrate what happens when
    the business collects less data overall.
    """
    all_rows = []
    base_time = datetime(2026, 8, 1, 8, 0, 0)

    for i in range(1, num_customers + 1):
        customer_id = f"C{str(i).zfill(4)}"
        start_time = base_time + timedelta(minutes=random.randint(0, 60 * 24 * 20))
        customer_events, _ = _simulate_one_customer(customer_id, start_time, include_enrichment)
        all_rows.extend(customer_events)

    dataframe = pd.DataFrame(all_rows)

    if thin:
        # Poor-data scenario: strip out several optional columns and
        # a chunk of late-stage events, simulating a business that
        # tracks much less about its customer journey.
        for col in ["channel", "transaction_id", "order_id"]:
            if col in dataframe.columns:
                dataframe = dataframe.drop(columns=[col])
        dataframe = dataframe[~dataframe["event"].isin(["delivery", "return", "review"])]

    if not include_enrichment:
        for col in ["abandonment_reason", "purchase_reason", "customer_satisfaction", "delivery_satisfaction"]:
            if col in dataframe.columns:
                dataframe = dataframe.drop(columns=[col])
        dataframe = dataframe[dataframe["event"] != "purchase_reason_recorded"]

    dataframe = dataframe.sort_values(["customer_id", "timestamp"]).reset_index(drop=True)
    return dataframe


def main():
    output_dir = os.path.join(os.path.dirname(__file__), "data")
    os.makedirs(output_dir, exist_ok=True)

    print("Generating Dataset 1: Normal (with intentional measurement gaps)...")
    normal_df = generate_dataset(num_customers=1600, include_enrichment=False, thin=False)
    normal_path = os.path.join(output_dir, "demo_online_shopping_data.csv")
    normal_df.to_csv(normal_path, index=False)
    print(f"  -> {normal_path} ({len(normal_df)} rows, {normal_df['customer_id'].nunique()} customers)")

    print("Generating Dataset 2: Better data (includes enrichment fields)...")
    random.seed(43)
    better_df = generate_dataset(num_customers=1600, include_enrichment=True, thin=False)
    better_path = os.path.join(output_dir, "demo_online_shopping_data_better.csv")
    better_df.to_csv(better_path, index=False)
    print(f"  -> {better_path} ({len(better_df)} rows, {better_df['customer_id'].nunique()} customers)")

    print("Generating Dataset 3: Poor/incomplete data...")
    random.seed(44)
    poor_df = generate_dataset(num_customers=1000, include_enrichment=False, thin=True)
    poor_path = os.path.join(output_dir, "demo_online_shopping_data_poor.csv")
    poor_df.to_csv(poor_path, index=False)
    print(f"  -> {poor_path} ({len(poor_df)} rows, {poor_df['customer_id'].nunique()} customers)")

    print("Done.")


if __name__ == "__main__":
    main()
